### ISSUE TITLE
Error when running

### ISSUE THREAD

**Issue by JoshuaSmeda** [surajsinghbisht054/py_banner_grabber#1]
python port.py -t 192.168.1.10 -p 22

######################################################
                By S.S.B Group                          
######################################################

    Suraj Singh
    Admin
    S.S.B Group
    surajsinghbisht054@gmail.com
    http://bitforestinfo.blogspot.com/

    Note: We Feel Proud To Be Indian
######################################################

[*] IP Address Detected : 192.168.1.10 | Num. Of Port Detected : 1
[*] Open Ports Verified.
[+] IP : 192.168.1.10 | Ports : ['22']
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "port.py", line 148, in banner_ip
    s.connect((address, port))
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
**TypeError: an integer is required**

************************************************** 

************************************************** 

[+] Scan Started On  Tue Feb 26 08:40:26 2019
[+] Scan Finished On Tue Feb 26 08:40:26 2019
[+] Total Time Taken  0.000930070877075  Seconds 

************************************************** 

 Thanks For Using My Program by SSB

**Comment by bonkc** [comment]
At line 148 add a cast to int for port like so. s.connect((address, int(port)))

**Comment by JoshuaSmeda** [comment]
Thanks for the response,

I've created a pull request with your fix in it. Please review and accept to update the file.
